///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PdfToExcel
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_CheckBoxLA7(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Step 23\r\nMouse Left Click item 'checkboxInfo' at 5;10.", checkboxInfo);
			Ranorex.CheckBox chkbox = repo.ValidationReportForm.TabPageSterilization.LA7;
			
			if (chkbox.Checked) {
				chkbox.Click();
			}
        }

        public void Mouse_Click_CheckBoxUseF0Calculation(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Step 23\r\nMouse Left Click item 'checkboxInfo' at 8;13.", checkboxInfo);
			
			Ranorex.CheckBox chkbox = repo.ValidationReportForm.CheckBoxUseF0Calculation;
			
			if (!chkbox.Checked) {
				chkbox.Click();
			}
        }

        public void Mouse_Click_LA1_LA2(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Step 22\r\nMouse Left Click item 'checkboxInfo' at 7;8.", checkboxInfo);
			Ranorex.CheckBox chkboxLA1 = repo.ValidationReportForm.TabPageSterilization.LA1;
			Ranorex.CheckBox chkboxLA2 = repo.ValidationReportForm.TabPageSterilization.LA2;
			
			if (!chkboxLA1.Checked) {
				chkboxLA1.Click();
			}
			if (!chkboxLA2.Checked) {
				chkboxLA2.Click();
			}
        }

        public void Mouse_Click_LC2_LC3(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Step 11\r\nMouse Left Click item 'checkboxInfo' at 10;6.", checkboxInfo);
			
			Ranorex.CheckBox chkboxLC2 = repo.ValidationReportForm.TabPageSterilization.LC2;
			Ranorex.CheckBox chkboxLC3 = repo.ValidationReportForm.TabPageSterilization.LC3;
			
			if (!chkboxLC2.Checked) {
				chkboxLC2.Click();
			}
			if (!chkboxLC3.Checked) {
				chkboxLC3.Click();
			}
        }

        public void Mouse_Click_CheckBoxUseSaturatedSteam(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'checkboxInfo' at 9;12.", checkboxInfo);
			
			Ranorex.CheckBox chkbox = repo.ValidationReportForm.TabPageSterilization.CheckBoxUseSaturatedSteam;
			
			if (!chkbox.Checked) {
				checkboxInfo.FindAdapter<CheckBox>().Click("9;12");
			}
        }

        public void Mouse_Click_CheckBoxMaxTempDifFirst60Sec(RepoItemInfo checkboxInfo)
        {
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'checkboxInfo' at 8;12.", checkboxInfo);
			
			Ranorex.CheckBox chkbox = repo.ValidationReportForm.TabPageSterilization.CheckBoxMaxTempDifFirst60Sec;
			
			if (!chkbox.Checked) {
				checkboxInfo.FindAdapter<CheckBox>().Click("8;12");
			}
        }

        public void DragSliders()
        {
			Slider sliderTemperature = repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.SliderTemperature;
			Slider sliderPressure = repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.SliderPressure;
			
			sliderTemperature.Click();
			
			for (int i = 0; i < 3; i++) {
				Keyboard.Press(System.Windows.Forms.Keys.Right);
			}
			
			sliderPressure.Click();
			
			for (int i = 0; i < 3; i++) {
				Keyboard.Press(System.Windows.Forms.Keys.Right);
			}
        }

    }
}
