///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PdfToExcel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b282078e-5829-4da7-a875-e1ac1a9bf427", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PdfToExcelRepository repository.
        /// </summary>
        public static PdfToExcelRepository repo = PdfToExcelRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CDataSessionManager.ISO17665ValidationReport' at 72;7.", repo.CDataSessionManager.ISO17665ValidationReportInfo, new RecordItemIndex(0));
            //repo.CDataSessionManager.ISO17665ValidationReport.Click(System.Windows.Forms.MouseButtons.Right, "72;7");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TilesContextMenuTilesMainViewModel.ViewReport' at 39;9.", repo.TilesContextMenuTilesMainViewModel.ViewReportInfo, new RecordItemIndex(1));
            //repo.TilesContextMenuTilesMainViewModel.ViewReport.Click("39;9");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderRightWindow' at 90;300.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderRightWindowInfo, new RecordItemIndex(2));
            //repo.ValidationPdfAdobeAcrobatProDC6.ReaderRightWindow.Click("90;300");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 960;277.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(3));
            //repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("960;277");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 1077;229.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(4));
            //repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("1077;229");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 945;570.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(5));
            //repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("945;570");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(6));
            //Delay.Duration(4000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ReaderChooseFolder' at 700;538.", repo.SaveAs.ReaderChooseFolderInfo, new RecordItemIndex(7));
            //repo.SaveAs.ReaderChooseFolder.Click("700;538");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at 48;13.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(8));
            //repo.SaveAs.ButtonSave.Click("48;13");
            //Delay.Milliseconds(0);
            
            // Step 2 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 2 √\r\nMouse Left Click item 'CDataSessionManager.Tools' at 24;9.", repo.CDataSessionManager.ToolsInfo, new RecordItemIndex(9));
            repo.CDataSessionManager.Tools.Click("24;9");
            Delay.Milliseconds(0);
            
            // Step 2 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 2 √\r\nMouse Left Click item 'Valsuite.ControlCenter' at 83;15.", repo.Valsuite.ControlCenterInfo, new RecordItemIndex(10));
            repo.Valsuite.ControlCenter.Click("83;15");
            Delay.Milliseconds(0);
            
            // Step 2 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 2 √\r\nMouse Left Click item 'CDataSessionManager.ContainerNoOfDisplayedDecimals.Resolution' at 76;13.", repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.ResolutionInfo, new RecordItemIndex(11));
            repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.Resolution.Click("76;13");
            Delay.Milliseconds(0);
            
            // Step 2 √
            DragSliders();
            Delay.Milliseconds(0);
            
            // Step 2 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 2 √\r\nMouse Left Click item 'CDataSessionManager.ContainerNoOfDisplayedDecimals.Apply' at 47;22.", repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.ApplyInfo, new RecordItemIndex(13));
            repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.Apply.Click("47;22");
            Delay.Milliseconds(0);
            
            // Step 3 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 3 √\r\nMouse Left Click item 'CDataSessionManager.File' at 16;10.", repo.CDataSessionManager.FileInfo, new RecordItemIndex(14));
            repo.CDataSessionManager.File.Click("16;10");
            Delay.Milliseconds(0);
            
            // Step 3 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 3 √\r\nMouse Left Click item 'Valsuite.OpenD7xFile' at 77;11.", repo.Valsuite.OpenD7xFileInfo, new RecordItemIndex(15));
            repo.Valsuite.OpenD7xFile.Click("77;11");
            Delay.Milliseconds(0);
            
            // Step 3 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 3 √\r\nMouse Left Click item 'Open.SystemItemNameDisplay' at 70;11.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(16));
            repo.Open.SystemItemNameDisplay.Click("70;11");
            Delay.Milliseconds(0);
            
            // Step 3 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 3 √\r\nMouse Left Click item 'Open.ButtonOpen' at 30;16.", repo.Open.ButtonOpenInfo, new RecordItemIndex(17));
            repo.Open.ButtonOpen.Click("30;16");
            Delay.Milliseconds(0);
            
            // Step 4 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 4 √\r\nMouse Left Click item 'CDataSessionManager.SessionAdd' at 15;9.", repo.CDataSessionManager.SessionAddInfo, new RecordItemIndex(18));
            repo.CDataSessionManager.SessionAdd.Click("15;9");
            Delay.Milliseconds(0);
            
            // Step 4 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 4 √\r\nMouse Left Click item 'Valsuite.Report' at 123;6.", repo.Valsuite.ReportInfo, new RecordItemIndex(19));
            repo.Valsuite.Report.Click("123;6");
            Delay.Milliseconds(0);
            
            // Step 4 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 4 √\r\nMouse Left Click item 'Valsuite.ISO17665Validation' at 120;11.", repo.Valsuite.ISO17665ValidationInfo, new RecordItemIndex(20));
            repo.Valsuite.ISO17665Validation.Click("120;11");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 5 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageSterilization.ProcessTemperature' at 33;4.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureInfo, new RecordItemIndex(21));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperature.DoubleClick("33;4");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 5 √\r\nKey sequence '134{Return}' with focus on 'ValidationReportForm.TabPageSterilization.ProcessTemperature'.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureInfo, new RecordItemIndex(22));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperature.PressKeys("134{Return}");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 5 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageSterilization.ProcessTemperatureBand' at 14;7.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureBandInfo, new RecordItemIndex(23));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureBand.DoubleClick("14;7");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 5 √\r\nKey sequence '3{Return}' with focus on 'ValidationReportForm.TabPageSterilization.ProcessTemperatureBand'.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureBandInfo, new RecordItemIndex(24));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureBand.PressKeys("3{Return}");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Mouse_Click_CheckBoxMaxTempDifFirst60Sec(repo.ValidationReportForm.TabPageSterilization.CheckBoxMaxTempDifFirst60SecInfo);
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 5 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageSterilization.MaxTempDifFirst60Sec' at 31;8.", repo.ValidationReportForm.TabPageSterilization.MaxTempDifFirst60SecInfo, new RecordItemIndex(26));
            repo.ValidationReportForm.TabPageSterilization.MaxTempDifFirst60Sec.DoubleClick("31;8");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 5 √\r\nKey sequence '5{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MaxTempDifFirst60Sec'.", repo.ValidationReportForm.TabPageSterilization.MaxTempDifFirst60SecInfo, new RecordItemIndex(27));
            repo.ValidationReportForm.TabPageSterilization.MaxTempDifFirst60Sec.PressKeys("5{Return}");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Mouse_Click_CheckBoxUseSaturatedSteam(repo.ValidationReportForm.TabPageSterilization.CheckBoxUseSaturatedSteamInfo);
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 5 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSeconds' at 9;4.", repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSecondsInfo, new RecordItemIndex(29));
            repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSeconds.Click("9;4");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 5 √\r\nKey sequence '15{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSeconds'.", repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSecondsInfo, new RecordItemIndex(30));
            repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeSeconds.PressKeys("15{Return}");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 5 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.MinimumHoldingTime' at 10;10.", repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTimeInfo, new RecordItemIndex(31));
            repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTime.Click("10;10");
            Delay.Milliseconds(0);
            
            // Step 5 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 5 √\r\nKey sequence '3{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MinimumHoldingTime'.", repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTimeInfo, new RecordItemIndex(32));
            repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTime.PressKeys("3{Return}");
            Delay.Milliseconds(0);
            
            // Step 6 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 6 √\r\nMouse Left Click item 'ValidationReportForm.ButtonSaveTemplate' at 95;14.", repo.ValidationReportForm.ButtonSaveTemplateInfo, new RecordItemIndex(33));
            repo.ValidationReportForm.ButtonSaveTemplate.Click("95;14");
            Delay.Milliseconds(0);
            
            // Step 6 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 6 √\r\nMouse Left Click item 'DBTemplateForm.TemplateName' at 111;6.", repo.DBTemplateForm.TemplateNameInfo, new RecordItemIndex(34));
            repo.DBTemplateForm.TemplateName.Click("111;6");
            Delay.Milliseconds(0);
            
            // Step 6 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 6 √\r\nKey sequence 'EN17665 800I 134C{Return}' with focus on 'DBTemplateForm.TemplateName'.", repo.DBTemplateForm.TemplateNameInfo, new RecordItemIndex(35));
            repo.DBTemplateForm.TemplateName.PressKeys("EN17665 800I 134C{Return}");
            Delay.Milliseconds(0);
            
            // Step 7 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 7 √\r\nMouse Left Click item 'Acrobat.ButtonYes' at 51;19.", repo.Acrobat.ButtonYesInfo, new RecordItemIndex(36));
            repo.Acrobat.ButtonYes.Click("51;19");
            Delay.Milliseconds(0);
            
            // Step 8 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 8 √\r\nMouse Left Click item 'ValidationReportForm.ButtonCancel' at 66;14.", repo.ValidationReportForm.ButtonCancelInfo, new RecordItemIndex(37));
            repo.ValidationReportForm.ButtonCancel.Click("66;14");
            Delay.Milliseconds(0);
            
            // Step 9 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 9 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo' at 76;10.", repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6MoInfo, new RecordItemIndex(38));
            repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo.Click(System.Windows.Forms.MouseButtons.Right, "76;10");
            Delay.Milliseconds(0);
            
            // Step 9 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 9 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.AddISO17665ValidationReport' at 130;12.", repo.TilesContextMenuTilesMainViewModel.AddISO17665ValidationReportInfo, new RecordItemIndex(39));
            repo.TilesContextMenuTilesMainViewModel.AddISO17665ValidationReport.Click("130;12");
            Delay.Milliseconds(0);
            
            // Step 10 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 10 √\r\nMouse Left Click item 'ValidationReportForm.ButtonLoadTemplate' at 80;12.", repo.ValidationReportForm.ButtonLoadTemplateInfo, new RecordItemIndex(40));
            repo.ValidationReportForm.ButtonLoadTemplate.Click("80;12");
            Delay.Milliseconds(0);
            
            // Step 10 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 10 √\r\nMouse Left Click item 'DBTemplateForm.TemplateName' at 112;3.", repo.DBTemplateForm.TemplateNameInfo, new RecordItemIndex(41));
            repo.DBTemplateForm.TemplateName.Click("112;3");
            Delay.Milliseconds(0);
            
            // Step 10 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 10 √\r\nKey sequence 'EN17665 800I 134C' with focus on 'DBTemplateForm.TemplateName'.", repo.DBTemplateForm.TemplateNameInfo, new RecordItemIndex(42));
            repo.DBTemplateForm.TemplateName.PressKeys("EN17665 800I 134C");
            Delay.Milliseconds(0);
            
            // Step 10 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 10 √\r\nMouse Left Click item 'DBTemplateForm.BtnOK' at 32;13.", repo.DBTemplateForm.BtnOKInfo, new RecordItemIndex(43));
            repo.DBTemplateForm.BtnOK.Click("32;13");
            Delay.Milliseconds(0);
            
            // Step 11 √
            Mouse_Click_LC2_LC3(repo.ValidationReportForm.TabPageSterilization.LC2Info);
            Delay.Milliseconds(0);
            
            // Step 12 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 12 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 80;11.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(45));
            repo.ValidationReportForm.ButtonOk.Click("80;11");
            Delay.Milliseconds(0);
            
            // Step 13 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 13 √\r\nMouse Left Click item 'CDataSessionManager.File' at 15;14.", repo.CDataSessionManager.FileInfo, new RecordItemIndex(46));
            repo.CDataSessionManager.File.Click("15;14");
            Delay.Milliseconds(0);
            
            // Step 13 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 13 √\r\nMouse Left Click item 'Valsuite.PrintPreview' at 79;10.", repo.Valsuite.PrintPreviewInfo, new RecordItemIndex(47));
            repo.Valsuite.PrintPreview.Click("79;10");
            Delay.Milliseconds(0);
            
            // Step 13 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 13 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 10;10.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(48));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("10;10");
            Delay.Milliseconds(0);
            
            // Step 13 TODO: Excel export
            Report.Log(ReportLevel.Info, "Mouse", "Step 13 TODO: Excel export\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow8' at 41;10.", repo.ReportSettingsForm.ViewReportRow8Info, new RecordItemIndex(49));
            repo.ReportSettingsForm.ViewReportRow8.Click("41;10");
            Delay.Milliseconds(0);
            
            // Step 13 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 13 √\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 43;14.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(50));
            repo.ReportSettingsForm.BtnOk.Click("43;14");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerReaderRightWindow' at 90;300.", repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerReaderRightWindowInfo, new RecordItemIndex(51));
            repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerReaderRightWindow.Click("90;300");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow' at 945;285.", repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindowInfo, new RecordItemIndex(52));
            repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow.Click("945;285");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow' at 1078;227.", repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindowInfo, new RecordItemIndex(53));
            repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow.Click("1078;227");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow' at 954;575.", repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindowInfo, new RecordItemIndex(54));
            repo.ModernSterilizerPdfAdobeAcrobatPr.ModernSterilizerChooseFormatWindow.Click("954;575");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Delay", "EXPORT PDF TO EXCEL\r\nWaiting for 4s.", new RecordItemIndex(55));
            Delay.Duration(4000, false);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'SaveAs.ReaderChooseFolder' at 672;534.", repo.SaveAs.ReaderChooseFolderInfo, new RecordItemIndex(56));
            repo.SaveAs.ReaderChooseFolder.Click("672;534");
            Delay.Milliseconds(0);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'SaveAs.ButtonSave' at 54;10.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(57));
            repo.SaveAs.ButtonSave.Click("54;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(58));
            Delay.Duration(2000, false);
            
            // EXPORT PDF TO EXCEL
            Report.Log(ReportLevel.Info, "Mouse", "EXPORT PDF TO EXCEL\r\nMouse Left Click item 'ModernSterilizerPdfAdobeAcrobatPr.Close' at 16;10.", repo.ModernSterilizerPdfAdobeAcrobatPr.CloseInfo, new RecordItemIndex(59));
            repo.ModernSterilizerPdfAdobeAcrobatPr.Close.Click("16;10");
            Delay.Milliseconds(0);
            
            // Step 15 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 15 √\r\nMouse Left Click item 'CDataSessionManager.Close' at 8;6.", repo.CDataSessionManager.CloseInfo, new RecordItemIndex(60));
            repo.CDataSessionManager.Close.Click("8;6");
            Delay.Milliseconds(0);
            
            // Step 16 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 16 √\r\nMouse Left Click item 'CDataSessionManager.Tools' at 18;11.", repo.CDataSessionManager.ToolsInfo, new RecordItemIndex(61));
            repo.CDataSessionManager.Tools.Click("18;11");
            Delay.Milliseconds(0);
            
            // Step 16 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 16 √\r\nMouse Left Click item 'Valsuite.ControlCenter' at 84;12.", repo.Valsuite.ControlCenterInfo, new RecordItemIndex(62));
            repo.Valsuite.ControlCenter.Click("84;12");
            Delay.Milliseconds(0);
            
            // Step 16 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 16 √\r\nMouse Left Click item 'CDataSessionManager.ContainerNoOfDisplayedDecimals.Resolution' at 73;16.", repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.ResolutionInfo, new RecordItemIndex(63));
            repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.Resolution.Click("73;16");
            Delay.Milliseconds(0);
            
            // Step 16 √
            DragSliders();
            Delay.Milliseconds(0);
            
            // Step 16 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 16 √\r\nMouse Left Click item 'CDataSessionManager.ContainerNoOfDisplayedDecimals.Apply' at 64;15.", repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.ApplyInfo, new RecordItemIndex(65));
            repo.CDataSessionManager.ContainerNoOfDisplayedDecimals.Apply.Click("64;15");
            Delay.Milliseconds(0);
            
            // Step 17 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 17 √\r\nMouse Left Click item 'CDataSessionManager.File' at 14;11.", repo.CDataSessionManager.FileInfo, new RecordItemIndex(66));
            repo.CDataSessionManager.File.Click("14;11");
            Delay.Milliseconds(0);
            
            // Step 17 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 17 √\r\nMouse Left Click item 'Valsuite.OpenD7xFile' at 100;6.", repo.Valsuite.OpenD7xFileInfo, new RecordItemIndex(67));
            repo.Valsuite.OpenD7xFile.Click("100;6");
            Delay.Milliseconds(0);
            
            // Step 17 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 17 √\r\nMouse Left Click item 'Open.SystemItemNameDisplay2' at 20;8.", repo.Open.SystemItemNameDisplay2Info, new RecordItemIndex(68));
            repo.Open.SystemItemNameDisplay2.Click("20;8");
            Delay.Milliseconds(0);
            
            // Step 17 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 17 √\r\nMouse Left Click item 'Open.ButtonOpen' at 54;12.", repo.Open.ButtonOpenInfo, new RecordItemIndex(69));
            repo.Open.ButtonOpen.Click("54;12");
            Delay.Milliseconds(0);
            
            // Step 18 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 18 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo' at 70;4.", repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6MoInfo, new RecordItemIndex(70));
            repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo.Click(System.Windows.Forms.MouseButtons.Right, "70;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TilesContextMenuTilesMainViewModel' at Center.", repo.TilesContextMenuTilesMainViewModel.SelfInfo, new RecordItemIndex(71));
            repo.TilesContextMenuTilesMainViewModel.Self.MoveTo();
            Delay.Milliseconds(0);
            
            // Step 18 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 18 √\r\nMouse scroll Vertical by -720 units.", new RecordItemIndex(72));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            // Step 18 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 18 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.AddTimeMarker' at 27;2.", repo.TilesContextMenuTilesMainViewModel.AddTimeMarkerInfo, new RecordItemIndex(73));
            repo.TilesContextMenuTilesMainViewModel.AddTimeMarker.Click("27;2");
            Delay.Milliseconds(0);
            
            // Step 18 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 18 √\r\nMouse Left Click item 'TimeMarkerForm.BtnOk' at 43;11.", repo.TimeMarkerForm.BtnOkInfo, new RecordItemIndex(74));
            repo.TimeMarkerForm.BtnOk.Click("43;11");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.TimeMarker1' at 53;8.", repo.CDataSessionManager.SessionLeftContainer.TimeMarker1Info, new RecordItemIndex(75));
            repo.CDataSessionManager.SessionLeftContainer.TimeMarker1.Click(System.Windows.Forms.MouseButtons.Right, "53;8");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Move item 'TilesContextMenuTilesMainViewModel' at Center.", repo.TilesContextMenuTilesMainViewModel.SelfInfo, new RecordItemIndex(76));
            repo.TilesContextMenuTilesMainViewModel.Self.MoveTo();
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.Edit' at 10;9.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(77));
            repo.TilesContextMenuTilesMainViewModel.Edit.Click("10;9");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Click item 'TimeMarkerForm.GetSingleTimeControl1.TextboxHours' at 7;7.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxHoursInfo, new RecordItemIndex(78));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxHours.Click("7;7");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 19 √\r\nKey sequence '9' with focus on 'TimeMarkerForm.GetSingleTimeControl1.TextboxHours'.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxHoursInfo, new RecordItemIndex(79));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxHours.PressKeys("9");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Click item 'TimeMarkerForm.GetSingleTimeControl1.TextboxMinutes' at 8;7.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxMinutesInfo, new RecordItemIndex(80));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxMinutes.Click("8;7");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 19 √\r\nKey sequence '22' with focus on 'TimeMarkerForm.GetSingleTimeControl1.TextboxMinutes'.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxMinutesInfo, new RecordItemIndex(81));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxMinutes.PressKeys("22");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Click item 'TimeMarkerForm.GetSingleTimeControl1.TextboxSeconds' at 5;7.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxSecondsInfo, new RecordItemIndex(82));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxSeconds.Click("5;7");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 19 √\r\nKey sequence '42' with focus on 'TimeMarkerForm.GetSingleTimeControl1.TextboxSeconds'.", repo.TimeMarkerForm.GetSingleTimeControl1.TextboxSecondsInfo, new RecordItemIndex(83));
            repo.TimeMarkerForm.GetSingleTimeControl1.TextboxSeconds.PressKeys("42");
            Delay.Milliseconds(0);
            
            // Step 19 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 19 √\r\nMouse Left Click item 'TimeMarkerForm.BtnOk' at 38;13.", repo.TimeMarkerForm.BtnOkInfo, new RecordItemIndex(84));
            repo.TimeMarkerForm.BtnOk.Click("38;13");
            Delay.Milliseconds(0);
            
            // Step 20 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 20 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo' at 103;8.", repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6MoInfo, new RecordItemIndex(85));
            repo.CDataSessionManager.SessionLeftContainer.CUsersMraDocuments296OQTS00R6Mo.Click(System.Windows.Forms.MouseButtons.Right, "103;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TilesContextMenuTilesMainViewModel' at Center.", repo.TilesContextMenuTilesMainViewModel.SelfInfo, new RecordItemIndex(86));
            repo.TilesContextMenuTilesMainViewModel.Self.MoveTo();
            Delay.Milliseconds(0);
            
            // Step 20 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 20 √\r\nMouse Left Move item 'TilesContextMenuTilesMainViewModel.SomeGrip' at Center.", repo.TilesContextMenuTilesMainViewModel.SomeGripInfo, new RecordItemIndex(87));
            repo.TilesContextMenuTilesMainViewModel.SomeGrip.MoveTo();
            Delay.Milliseconds(0);
            
            // Step 20 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 20 √\r\nMouse scroll Vertical by -720 units.", new RecordItemIndex(88));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            // Step 20 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 20 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.AddISO17665ValidationReport' at 148;6.", repo.TilesContextMenuTilesMainViewModel.AddISO17665ValidationReportInfo, new RecordItemIndex(89));
            repo.TilesContextMenuTilesMainViewModel.AddISO17665ValidationReport.Click("148;6");
            Delay.Milliseconds(0);
            
            // Step 21 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 21 √\r\nMouse Left Click item 'ValidationReportForm.PreselectedTimestamps' at 49;11.", repo.ValidationReportForm.PreselectedTimestampsInfo, new RecordItemIndex(90));
            repo.ValidationReportForm.PreselectedTimestamps.Click("49;11");
            Delay.Milliseconds(0);
            
            // Step 21 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 21 √\r\nMouse Left Click item 'List1000.TimeMarker1' at 45;8.", repo.List1000.TimeMarker1Info, new RecordItemIndex(91));
            repo.List1000.TimeMarker1.Click("45;8");
            Delay.Milliseconds(0);
            
            // Step 22 √
            Mouse_Click_CheckBoxMaxTempDifFirst60Sec(repo.ValidationReportForm.TabPageSterilization.CheckBoxMaxTempDifFirst60SecInfo);
            Delay.Milliseconds(0);
            
            // Step 22 √
            Mouse_Click_LA1_LA2(repo.ValidationReportForm.TabPageSterilization.LA1Info);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'ValidationReportForm.LethalityCalculation' at 39;9.", repo.ValidationReportForm.LethalityCalculationInfo, new RecordItemIndex(94));
            repo.ValidationReportForm.LethalityCalculation.Click("39;9");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Mouse_Click_CheckBoxUseF0Calculation(repo.ValidationReportForm.TabPageF0Calculation.CheckBoxUseF0CalculationInfo);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'ValidationReportForm.TabPageF0Calculation.RadioButtonF0InHoldingTime' at 6;12.", repo.ValidationReportForm.TabPageF0Calculation.RadioButtonF0InHoldingTimeInfo, new RecordItemIndex(96));
            repo.ValidationReportForm.TabPageF0Calculation.RadioButtonF0InHoldingTime.Click("6;12");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'ValidationReportForm.TabPageF0Calculation.Open' at 4;11.", repo.ValidationReportForm.TabPageF0Calculation.OpenInfo, new RecordItemIndex(97));
            repo.ValidationReportForm.TabPageF0Calculation.Open.Click("4;11");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'List1000.ListItemF0' at 17;8.", repo.List1000.ListItemF0Info, new RecordItemIndex(98));
            repo.List1000.ListItemF0.Click("17;8");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit' at 21;12.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEditInfo, new RecordItemIndex(99));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit.Click("21;12");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey 'Ctrl+A' Press with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEditInfo, new RecordItemIndex(100));
            Keyboard.PrepareFocus(repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey sequence '121,11{Tab}' with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEditInfo, new RecordItemIndex(101));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit.PressKeys("121,11{Tab}");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 23 √\r\nMouse Left Click item 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit1' at 44;9.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1Info, new RecordItemIndex(102));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1.Click("44;9");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey 'Ctrl+A' Press with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit1'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1Info, new RecordItemIndex(103));
            Keyboard.PrepareFocus(repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey sequence '91,11{Tab}' with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit1'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1Info, new RecordItemIndex(104));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit1.PressKeys("91,11{Tab}");
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey 'Ctrl+A' Press with focus on 'ValidationReportForm'.", repo.ValidationReportForm.SelfInfo, new RecordItemIndex(105));
            Keyboard.PrepareFocus(repo.ValidationReportForm.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey 'Ctrl+A' Press with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit2'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit2Info, new RecordItemIndex(106));
            Keyboard.PrepareFocus(repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit2);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Step 23 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 23 √\r\nKey 'Ctrl+A' Press with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit3'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3Info, new RecordItemIndex(107));
            Keyboard.PrepareFocus(repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Step 24 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 24 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 55;6.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(108));
            repo.ValidationReportForm.ButtonOk.Click("55;6");
            Delay.Milliseconds(0);
            
            // Step 25 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 25 √\r\nMouse Left Click item 'CDataSessionManager.PrintPreview' at 13;20.", repo.CDataSessionManager.PrintPreviewInfo, new RecordItemIndex(109));
            repo.CDataSessionManager.PrintPreview.Click("13;20");
            Delay.Milliseconds(0);
            
            // Step 25 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 25 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 87;8.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(110));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("87;8");
            Delay.Milliseconds(0);
            
            // Step 25 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 25 √\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow10' at 40;14.", repo.ReportSettingsForm.ViewReportRow10Info, new RecordItemIndex(111));
            repo.ReportSettingsForm.ViewReportRow10.Click("40;14");
            Delay.Milliseconds(0);
            
            // Step 25 √ TODO: Excel validation
            Report.Log(ReportLevel.Info, "Mouse", "Step 25 √ TODO: Excel validation\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 46;14.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(112));
            repo.ReportSettingsForm.BtnOk.Click("46;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderRightWindow' at 90;300.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderRightWindowInfo, new RecordItemIndex(113));
            repo.ValidationPdfAdobeAcrobatProDC6.ReaderRightWindow.Click("90;300");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 960;277.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(114));
            repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("960;277");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 1077;229.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(115));
            repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("1077;229");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow' at 945;570.", repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindowInfo, new RecordItemIndex(116));
            repo.ValidationPdfAdobeAcrobatProDC6.ReaderChooseFormatWindow.Click("945;570");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(117));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ReaderChooseFolder' at 700;538.", repo.SaveAs.ReaderChooseFolderInfo, new RecordItemIndex(118));
            repo.SaveAs.ReaderChooseFolder.Click("700;538");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at 48;13.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(119));
            repo.SaveAs.ButtonSave.Click("48;13");
            Delay.Milliseconds(0);
            
            // Step 28 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 28 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.ISO17665ValidationReport' at 80;11.", repo.CDataSessionManager.SessionLeftContainer.ISO17665ValidationReportInfo, new RecordItemIndex(120));
            repo.CDataSessionManager.SessionLeftContainer.ISO17665ValidationReport.Click(System.Windows.Forms.MouseButtons.Right, "80;11");
            Delay.Milliseconds(0);
            
            // Step 28 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 28 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.EditButton' at 61;6.", repo.TilesContextMenuTilesMainViewModel.EditButtonInfo, new RecordItemIndex(121));
            repo.TilesContextMenuTilesMainViewModel.EditButton.Click("61;6");
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 29 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageSterilization.ProcessTemperature' at Center.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureInfo, new RecordItemIndex(122));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperature.DoubleClick();
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 29 √\r\nKey sequence '133{Return}' with focus on 'ValidationReportForm.TabPageSterilization.ProcessTemperature'.", repo.ValidationReportForm.TabPageSterilization.ProcessTemperatureInfo, new RecordItemIndex(123));
            repo.ValidationReportForm.TabPageSterilization.ProcessTemperature.PressKeys("133{Return}");
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 29 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutes' at Center.", repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutesInfo, new RecordItemIndex(124));
            repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutes.Click();
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 29 √\r\nKey sequence '1{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutes'.", repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutesInfo, new RecordItemIndex(125));
            repo.ValidationReportForm.TabPageSterilization.MaxEquilibrationTimeMinutes.PressKeys("1{Return}");
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 29 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.MinimumHoldingTime' at Center.", repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTimeInfo, new RecordItemIndex(126));
            repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTime.Click();
            Delay.Milliseconds(0);
            
            // Step 29 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 29 √\r\nKey sequence '13{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MinimumHoldingTime'.", repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTimeInfo, new RecordItemIndex(127));
            repo.ValidationReportForm.TabPageSterilization.MinimumHoldingTime.PressKeys("13{Return}");
            Delay.Milliseconds(0);
            
            // Step 29 √
            Mouse_Click_CheckBoxLA7(repo.ValidationReportForm.TabPageSterilization.LA7Info);
            Delay.Milliseconds(0);
            
            // Step 30 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 30 √\r\nMouse Left Click item 'ValidationReportForm.LethalityCalculation' at 42;8.", repo.ValidationReportForm.LethalityCalculationInfo, new RecordItemIndex(129));
            repo.ValidationReportForm.LethalityCalculation.Click("42;8");
            Delay.Milliseconds(0);
            
            // Step 30 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 30 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit3' at 18;7.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3Info, new RecordItemIndex(130));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3.DoubleClick("18;7");
            Delay.Milliseconds(0);
            
            // Step 30 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 30 √\r\nKey sequence '200{Return}' with focus on 'ValidationReportForm.TabPageF0Calculation1.UpDownEdit3'.", repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3Info, new RecordItemIndex(131));
            repo.ValidationReportForm.TabPageF0Calculation1.UpDownEdit3.PressKeys("200{Return}");
            Delay.Milliseconds(0);
            
            // Step 31 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 31 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 88;10.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(132));
            repo.ValidationReportForm.ButtonOk.Click("88;10");
            Delay.Milliseconds(0);
            
            // Step 32 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 32 √\r\nMouse Left Click item 'CDataSessionManager.PrintPreview' at 13;18.", repo.CDataSessionManager.PrintPreviewInfo, new RecordItemIndex(133));
            repo.CDataSessionManager.PrintPreview.Click("13;18");
            Delay.Milliseconds(0);
            
            // Step 32 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 32 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 30;10.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(134));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("30;10");
            Delay.Milliseconds(0);
            
            // Step 32 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 32 √\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow10' at 41;10.", repo.ReportSettingsForm.ViewReportRow10Info, new RecordItemIndex(135));
            repo.ReportSettingsForm.ViewReportRow10.Click("41;10");
            Delay.Milliseconds(0);
            
            // Step 33 √ TODO: Excel validation
            Report.Log(ReportLevel.Info, "Mouse", "Step 33 √ TODO: Excel validation\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 58;8.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(136));
            repo.ReportSettingsForm.BtnOk.Click("58;8");
            Delay.Milliseconds(0);
            
            // Step 35 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 35 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.ISO17665ValidationReport' at 102;12.", repo.CDataSessionManager.SessionLeftContainer.ISO17665ValidationReportInfo, new RecordItemIndex(137));
            repo.CDataSessionManager.SessionLeftContainer.ISO17665ValidationReport.Click(System.Windows.Forms.MouseButtons.Right, "102;12");
            Delay.Milliseconds(0);
            
            // Step 35 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 35 √\r\nMouse Left Move item 'TilesContextMenuTilesMainViewModel.Edit' at .25;.25.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(138));
            repo.TilesContextMenuTilesMainViewModel.Edit.MoveTo(".25;.25");
            Delay.Milliseconds(0);
            
            // Step 35 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 35 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.Edit' at 10;9.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(139));
            repo.TilesContextMenuTilesMainViewModel.Edit.Click("10;9");
            Delay.Milliseconds(0);
            
            // Step 36 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 36 √\r\nMouse Left Click item 'ValidationReportForm.LethalityCalculation' at 33;5.", repo.ValidationReportForm.LethalityCalculationInfo, new RecordItemIndex(140));
            repo.ValidationReportForm.LethalityCalculation.Click("33;5");
            Delay.Milliseconds(0);
            
            // Step 36 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 36 √\r\nMouse Left Click item 'ValidationReportForm.TabPageF0Calculation1.TextboxMinutes' at 6;5.", repo.ValidationReportForm.TabPageF0Calculation1.TextboxMinutesInfo, new RecordItemIndex(141));
            repo.ValidationReportForm.TabPageF0Calculation1.TextboxMinutes.Click("6;5");
            Delay.Milliseconds(0);
            
            // Step 36 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 36 √\r\nKey sequence '13' with focus on 'ValidationReportForm.TabPageF0Calculation1.TextboxMinutes'.", repo.ValidationReportForm.TabPageF0Calculation1.TextboxMinutesInfo, new RecordItemIndex(142));
            repo.ValidationReportForm.TabPageF0Calculation1.TextboxMinutes.PressKeys("13");
            Delay.Milliseconds(0);
            
            // Step 36 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 36 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 67;11.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(143));
            repo.ValidationReportForm.ButtonOk.Click("67;11");
            Delay.Milliseconds(0);
            
            // Step 37 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 37 √\r\nMouse Left Click item 'CDataSessionManager.PrintPreview' at 16;12.", repo.CDataSessionManager.PrintPreviewInfo, new RecordItemIndex(144));
            repo.CDataSessionManager.PrintPreview.Click("16;12");
            Delay.Milliseconds(0);
            
            // Step 37 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 37 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 50;5.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(145));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("50;5");
            Delay.Milliseconds(0);
            
            // Step 37 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 37 √\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow10' at 41;11.", repo.ReportSettingsForm.ViewReportRow10Info, new RecordItemIndex(146));
            repo.ReportSettingsForm.ViewReportRow10.Click("41;11");
            Delay.Milliseconds(0);
            
            // Step 37 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 37 √\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 42;17.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(147));
            repo.ReportSettingsForm.BtnOk.Click("42;17");
            Delay.Milliseconds(0);
            
            // Step 40 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 40 √\r\nMouse Left Click item 'CDataSessionManager.Close' at 15;10.", repo.CDataSessionManager.CloseInfo, new RecordItemIndex(148));
            repo.CDataSessionManager.Close.Click("15;10");
            Delay.Milliseconds(0);
            
            // Step 41 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 41 √\r\nMouse Left Click item 'CDataSessionManager.File' at 15;14.", repo.CDataSessionManager.FileInfo, new RecordItemIndex(149));
            repo.CDataSessionManager.File.Click("15;14");
            Delay.Milliseconds(0);
            
            // Step 41 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 41 √\r\nMouse Left Click item 'Valsuite.OpenD7xFile' at 68;10.", repo.Valsuite.OpenD7xFileInfo, new RecordItemIndex(150));
            repo.Valsuite.OpenD7xFile.Click("68;10");
            Delay.Milliseconds(0);
            
            // Step 41 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 41 √\r\nMouse Left Click item 'Open.SystemItemNameDisplay1' at 65;9.", repo.Open.SystemItemNameDisplay1Info, new RecordItemIndex(151));
            repo.Open.SystemItemNameDisplay1.Click("65;9");
            Delay.Milliseconds(0);
            
            // Step 41 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 41 √\r\nMouse Left Click item 'Open.ButtonOpen' at 63;19.", repo.Open.ButtonOpenInfo, new RecordItemIndex(152));
            repo.Open.ButtonOpen.Click("63;19");
            Delay.Milliseconds(0);
            
            // Step 42 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 42 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.StartHoldingTime' at 77;5.", repo.CDataSessionManager.SessionLeftContainer.StartHoldingTimeInfo, new RecordItemIndex(153));
            repo.CDataSessionManager.SessionLeftContainer.StartHoldingTime.Click(System.Windows.Forms.MouseButtons.Right, "77;5");
            Delay.Milliseconds(0);
            
            // Step 42 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 42 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.View' at 15;7.", repo.TilesContextMenuTilesMainViewModel.ViewInfo, new RecordItemIndex(154));
            repo.TilesContextMenuTilesMainViewModel.View.Click("15;7");
            Delay.Milliseconds(0);
            
            // Step 43 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 43 √\r\nMouse Left Click item 'TimeMarkerForm.BtnOk' at 55;19.", repo.TimeMarkerForm.BtnOkInfo, new RecordItemIndex(155));
            repo.TimeMarkerForm.BtnOk.Click("55;19");
            Delay.Milliseconds(0);
            
            // Step 44 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 44 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.EndedHoldingTime1' at 66;10.", repo.CDataSessionManager.SessionLeftContainer.EndedHoldingTime1Info, new RecordItemIndex(156));
            repo.CDataSessionManager.SessionLeftContainer.EndedHoldingTime1.Click(System.Windows.Forms.MouseButtons.Right, "66;10");
            Delay.Milliseconds(0);
            
            // Step 44 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 44 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.View' at 20;4.", repo.TilesContextMenuTilesMainViewModel.ViewInfo, new RecordItemIndex(157));
            repo.TilesContextMenuTilesMainViewModel.View.Click("20;4");
            Delay.Milliseconds(0);
            
            // Step 45 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 45 √\r\nMouse Left Click item 'TimeMarkerForm.BtnOk' at 53;23.", repo.TimeMarkerForm.BtnOkInfo, new RecordItemIndex(158));
            repo.TimeMarkerForm.BtnOk.Click("53;23");
            Delay.Milliseconds(0);
            
            // Step 46 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 46 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.ValidationReport' at 37;11.", repo.CDataSessionManager.SessionLeftContainer.ValidationReportInfo, new RecordItemIndex(159));
            repo.CDataSessionManager.SessionLeftContainer.ValidationReport.Click(System.Windows.Forms.MouseButtons.Right, "37;11");
            Delay.Milliseconds(0);
            
            // Step 46 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 46 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.Edit' at 9;10.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(160));
            repo.TilesContextMenuTilesMainViewModel.Edit.Click("9;10");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 47 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.CheckBoxUseMaxTemperatureDifference' at 7;14.", repo.ValidationReportForm.TabPageSterilization.CheckBoxUseMaxTemperatureDifferenceInfo, new RecordItemIndex(161));
            repo.ValidationReportForm.TabPageSterilization.CheckBoxUseMaxTemperatureDifference.Click("7;14");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 47 √\r\nMouse Left DoubleClick item 'ValidationReportForm.TabPageSterilization.MaximumTemperatureDifference' at 2;7.", repo.ValidationReportForm.TabPageSterilization.MaximumTemperatureDifferenceInfo, new RecordItemIndex(162));
            repo.ValidationReportForm.TabPageSterilization.MaximumTemperatureDifference.DoubleClick("2;7");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 47 √\r\nKey sequence '1{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MaximumTemperatureDifference'.", repo.ValidationReportForm.TabPageSterilization.MaximumTemperatureDifferenceInfo, new RecordItemIndex(163));
            repo.ValidationReportForm.TabPageSterilization.MaximumTemperatureDifference.PressKeys("1{Return}");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 47 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.CheckBoxUseSaturatedSteam' at 4;10.", repo.ValidationReportForm.TabPageSterilization.CheckBoxUseSaturatedSteamInfo, new RecordItemIndex(164));
            repo.ValidationReportForm.TabPageSterilization.CheckBoxUseSaturatedSteam.Click("4;10");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 47 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.MaximumHoldingTime' at 8;8.", repo.ValidationReportForm.TabPageSterilization.MaximumHoldingTimeInfo, new RecordItemIndex(165));
            repo.ValidationReportForm.TabPageSterilization.MaximumHoldingTime.Click("8;8");
            Delay.Milliseconds(0);
            
            // Step 47 √
            Report.Log(ReportLevel.Info, "Keyboard", "Step 47 √\r\nKey sequence '39{Return}' with focus on 'ValidationReportForm.TabPageSterilization.MaximumHoldingTime'.", repo.ValidationReportForm.TabPageSterilization.MaximumHoldingTimeInfo, new RecordItemIndex(166));
            repo.ValidationReportForm.TabPageSterilization.MaximumHoldingTime.PressKeys("39{Return}");
            Delay.Milliseconds(0);
            
            // Step 48 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 48 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 88;11.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(167));
            repo.ValidationReportForm.ButtonOk.Click("88;11");
            Delay.Milliseconds(0);
            
            // Step 49 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 49 √\r\nMouse Left Click item 'CDataSessionManager.PrintPreview' at 16;16.", repo.CDataSessionManager.PrintPreviewInfo, new RecordItemIndex(168));
            repo.CDataSessionManager.PrintPreview.Click("16;16");
            Delay.Milliseconds(0);
            
            // Step 49 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 49 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 22;12.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(169));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("22;12");
            Delay.Milliseconds(0);
            
            // Step 49 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 49 √\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow9' at 41;8.", repo.ReportSettingsForm.ViewReportRow9Info, new RecordItemIndex(170));
            repo.ReportSettingsForm.ViewReportRow9.Click("41;8");
            Delay.Milliseconds(0);
            
            // Step 49 √ TODO: Excel validation
            Report.Log(ReportLevel.Info, "Mouse", "Step 49 √ TODO: Excel validation\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 52;19.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(171));
            repo.ReportSettingsForm.BtnOk.Click("52;19");
            Delay.Milliseconds(0);
            
            // Step 51 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 51 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.EndedHoldingTime2' at 47;9.", repo.CDataSessionManager.SessionLeftContainer.EndedHoldingTime2Info, new RecordItemIndex(172));
            repo.CDataSessionManager.SessionLeftContainer.EndedHoldingTime2.Click(System.Windows.Forms.MouseButtons.Right, "47;9");
            Delay.Milliseconds(0);
            
            // Step 51 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 51 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.View' at 12;5.", repo.TilesContextMenuTilesMainViewModel.ViewInfo, new RecordItemIndex(173));
            repo.TilesContextMenuTilesMainViewModel.View.Click("12;5");
            Delay.Milliseconds(0);
            
            // Step 52 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 52 √\r\nMouse Left Click item 'TimeMarkerForm.BtnOk' at 12;15.", repo.TimeMarkerForm.BtnOkInfo, new RecordItemIndex(174));
            repo.TimeMarkerForm.BtnOk.Click("12;15");
            Delay.Milliseconds(0);
            
            // Step 53 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 53 √\r\nMouse Right Click item 'CDataSessionManager.SessionLeftContainer.ValidationReport' at 43;5.", repo.CDataSessionManager.SessionLeftContainer.ValidationReportInfo, new RecordItemIndex(175));
            repo.CDataSessionManager.SessionLeftContainer.ValidationReport.Click(System.Windows.Forms.MouseButtons.Right, "43;5");
            Delay.Milliseconds(0);
            
            // Step 53 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 53 √\r\nMouse Left Move item 'TilesContextMenuTilesMainViewModel.Edit' at .25;.25.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(176));
            repo.TilesContextMenuTilesMainViewModel.Edit.MoveTo(".25;.25");
            Delay.Milliseconds(0);
            
            // Step 53 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 53 √\r\nMouse Left Click item 'TilesContextMenuTilesMainViewModel.Edit' at 10;9.", repo.TilesContextMenuTilesMainViewModel.EditInfo, new RecordItemIndex(177));
            repo.TilesContextMenuTilesMainViewModel.Edit.Click("10;9");
            Delay.Milliseconds(0);
            
            // Step 54 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 54 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeStart' at 118;8.", repo.ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeStartInfo, new RecordItemIndex(178));
            repo.ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeStart.Click("118;8");
            Delay.Milliseconds(0);
            
            // Step 54 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 54 √\r\nMouse Left Click item 'List1000.StartHoldingTime' at 64;8.", repo.List1000.StartHoldingTimeInfo, new RecordItemIndex(179));
            repo.List1000.StartHoldingTime.Click("64;8");
            Delay.Milliseconds(0);
            
            // Step 54 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 54 √\r\nMouse Left Click item 'ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeEnd' at 103;11.", repo.ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeEndInfo, new RecordItemIndex(180));
            repo.ValidationReportForm.TabPageSterilization.ComboBoxHoldingTimeEnd.Click("103;11");
            Delay.Milliseconds(0);
            
            // Step 54 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 54 √\r\nMouse Left Click item 'List1000.EndedHoldingTime2' at 63;5.", repo.List1000.EndedHoldingTime2Info, new RecordItemIndex(181));
            repo.List1000.EndedHoldingTime2.Click("63;5");
            Delay.Milliseconds(0);
            
            // Step 55 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 55 √\r\nMouse Left Click item 'ValidationReportForm.ButtonOk' at 65;15.", repo.ValidationReportForm.ButtonOkInfo, new RecordItemIndex(182));
            repo.ValidationReportForm.ButtonOk.Click("65;15");
            Delay.Milliseconds(0);
            
            // Step 56 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 56 √\r\nMouse Left Click item 'CDataSessionManager.PrintPreview' at 15;12.", repo.CDataSessionManager.PrintPreviewInfo, new RecordItemIndex(183));
            repo.CDataSessionManager.PrintPreview.Click("15;12");
            Delay.Milliseconds(0);
            
            // Step 56 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 56 √\r\nMouse Left Click item 'ReportSettingsForm.ButtonReportsSelectNone' at 13;17.", repo.ReportSettingsForm.ButtonReportsSelectNoneInfo, new RecordItemIndex(184));
            repo.ReportSettingsForm.ButtonReportsSelectNone.Click("13;17");
            Delay.Milliseconds(0);
            
            // Step 56 √
            Report.Log(ReportLevel.Info, "Mouse", "Step 56 √\r\nMouse Left Click item 'ReportSettingsForm.ViewReportRow9' at 44;6.", repo.ReportSettingsForm.ViewReportRow9Info, new RecordItemIndex(185));
            repo.ReportSettingsForm.ViewReportRow9.Click("44;6");
            Delay.Milliseconds(0);
            
            // Step 56 √ TODO: Excel Validation
            Report.Log(ReportLevel.Info, "Mouse", "Step 56 √ TODO: Excel Validation\r\nMouse Left Click item 'ReportSettingsForm.BtnOk' at 52;15.", repo.ReportSettingsForm.BtnOkInfo, new RecordItemIndex(186));
            repo.ReportSettingsForm.BtnOk.Click("52;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
